//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nat.API.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nat.API.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respuesta de servicio invalida.
        /// </summary>
        internal static string lioE_AfipRespNo {
            get {
                return ResourceManager.GetString("lioE_AfipRespNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encabezado de Autorizacion Invalido.
        /// </summary>
        internal static string lioE_AuthHeaderNo {
            get {
                return ResourceManager.GetString("lioE_AuthHeaderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en Solicitud de CAE: {0}-{1}.
        /// </summary>
        internal static string lioE_CAE_Err {
            get {
                return ResourceManager.GetString("lioE_CAE_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en Solicitud de CAE.
        /// </summary>
        internal static string lioE_CAE_No {
            get {
                return ResourceManager.GetString("lioE_CAE_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones en Solicitud de CAE: {0}-{1}.
        /// </summary>
        internal static string lioE_CAE_Obs {
            get {
                return ResourceManager.GetString("lioE_CAE_Obs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en Consulta de CAE: {0}-{1}.
        /// </summary>
        internal static string lioE_CAEQry_Err {
            get {
                return ResourceManager.GetString("lioE_CAEQry_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en Consulta de CAE.
        /// </summary>
        internal static string lioE_CAEQry_No {
            get {
                return ResourceManager.GetString("lioE_CAEQry_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones en Consulta de CAE: {0}-{1}.
        /// </summary>
        internal static string lioE_CAEQry_Obs {
            get {
                return ResourceManager.GetString("lioE_CAEQry_Obs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concepto Invalido..
        /// </summary>
        internal static string lioE_Concepto_No {
            get {
                return ResourceManager.GetString("lioE_Concepto_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de Correlatividad: ultimo documento autorizado es {0} y se intenta autorizar el documento {1}..
        /// </summary>
        internal static string lioE_Correlat_No {
            get {
                return ResourceManager.GetString("lioE_Correlat_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotizacion Invalida.
        /// </summary>
        internal static string lioE_Cotiz_No {
            get {
                return ResourceManager.GetString("lioE_Cotiz_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacion de Autorizacion no puede modificarse.
        /// </summary>
        internal static string lioE_Doc_AuthInfoMod {
            get {
                return ResourceManager.GetString("lioE_Doc_AuthInfoMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento Autorizado no puede eliminarse.
        /// </summary>
        internal static string lioE_Doc_AuthNoDelete {
            get {
                return ResourceManager.GetString("lioE_Doc_AuthNoDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentos {0} en espera de predecesor.
        /// </summary>
        internal static string lioE_DocCorrel {
            get {
                return ResourceManager.GetString("lioE_DocCorrel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos del Documento {0} Invalidos.
        /// </summary>
        internal static string lioE_DocNoData {
            get {
                return ResourceManager.GetString("lioE_DocNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF No Encontrado.
        /// </summary>
        internal static string lioE_Document_NoPrint {
            get {
                return ResourceManager.GetString("lioE_Document_NoPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos de Entrada de Usuario no encontrados.
        /// </summary>
        internal static string lioE_DocumentUser_No {
            get {
                return ResourceManager.GetString("lioE_DocumentUser_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errores en Envio de Documento a AFIP:.
        /// </summary>
        internal static string lioE_HeaderAuth {
            get {
                return ResourceManager.GetString("lioE_HeaderAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importe Invalido..
        /// </summary>
        internal static string lioE_Importe_No {
            get {
                return ResourceManager.GetString("lioE_Importe_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item {0} invalido.
        /// </summary>
        internal static string lioE_Item_No {
            get {
                return ResourceManager.GetString("lioE_Item_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificacion Unica de Documento Invalida.
        /// </summary>
        internal static string lioE_Key_No {
            get {
                return ResourceManager.GetString("lioE_Key_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo Electronico Invalido.
        /// </summary>
        internal static string lioE_Mail_No {
            get {
                return ResourceManager.GetString("lioE_Mail_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda Invalida..
        /// </summary>
        internal static string lioE_Moneda_No {
            get {
                return ResourceManager.GetString("lioE_Moneda_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credenciales Invalidas.
        /// </summary>
        internal static string lioE_NoCreds {
            get {
                return ResourceManager.GetString("lioE_NoCreds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de documentos a procesar vacia.
        /// </summary>
        internal static string lioE_NoDocs {
            get {
                return ResourceManager.GetString("lioE_NoDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en Recuperacion de {0}, Detalle:{1}..
        /// </summary>
        internal static string lioE_NoGet {
            get {
                return ResourceManager.GetString("lioE_NoGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Datos Estaticos no Encontrada.
        /// </summary>
        internal static string lioE_NoStatics {
            get {
                return ResourceManager.GetString("lioE_NoStatics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero de Comprobante Invalido..
        /// </summary>
        internal static string lioE_Nro_No {
            get {
                return ResourceManager.GetString("lioE_Nro_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no Encontrada o con forrmato erroneo..
        /// </summary>
        internal static string lioE_ObjectNoF {
            get {
                return ResourceManager.GetString("lioE_ObjectNoF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no Encontrado o con forrmato erroneo..
        /// </summary>
        internal static string lioE_ObjectNoM {
            get {
                return ResourceManager.GetString("lioE_ObjectNoM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Opcional [{0}] invalido..
        /// </summary>
        internal static string lioE_Opcional_No {
            get {
                return ResourceManager.GetString("lioE_Opcional_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento Original no Encontrado.
        /// </summary>
        internal static string lioE_OriginalNo {
            get {
                return ResourceManager.GetString("lioE_OriginalNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permiso de Importacion {0} Invalido.
        /// </summary>
        internal static string lioE_PermisoNo {
            get {
                return ResourceManager.GetString("lioE_PermisoNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en Impresion de Documento.
        /// </summary>
        internal static string lioE_PrintNo {
            get {
                return ResourceManager.GetString("lioE_PrintNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejecucion Previa aun no finalizada.
        /// </summary>
        internal static string lioE_ProcRun {
            get {
                return ResourceManager.GetString("lioE_ProcRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punto de Venta Invalido..
        /// </summary>
        internal static string lioE_Pventa_No {
            get {
                return ResourceManager.GetString("lioE_Pventa_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punto de Venta Invalido en Documento Asociado [{0}]..
        /// </summary>
        internal static string lioE_PvtaAsoc_No {
            get {
                return ResourceManager.GetString("lioE_PvtaAsoc_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron Campos dentro de la Plantilla de Reporte.
        /// </summary>
        internal static string lioE_Report_NoFields {
            get {
                return ResourceManager.GetString("lioE_Report_NoFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Datos de Origen de Reporte Invalido.
        /// </summary>
        internal static string lioE_ReportAssembly_No {
            get {
                return ResourceManager.GetString("lioE_ReportAssembly_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origen de Datos no Coincide con Plantilla se espera [{0}] y se encontro [{1}].
        /// </summary>
        internal static string lioE_ReportAssembly_NoMatch {
            get {
                return ResourceManager.GetString("lioE_ReportAssembly_NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo de Reporte Invalido.
        /// </summary>
        internal static string lioE_ReportField_No {
            get {
                return ResourceManager.GetString("lioE_ReportField_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Tipo Tabla no posee columnas.
        /// </summary>
        internal static string lioE_ReportField_NoColumns {
            get {
                return ResourceManager.GetString("lioE_ReportField_NoColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encuentran lineas de factura a imprimir.
        /// </summary>
        internal static string lioE_ReportLines_No {
            get {
                return ResourceManager.GetString("lioE_ReportLines_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propiedad {0} no encontrada en Origen de Datos.
        /// </summary>
        internal static string lioE_ReportProperty_No {
            get {
                return ResourceManager.GetString("lioE_ReportProperty_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origen de Datos de Reporte Invalido.
        /// </summary>
        internal static string lioE_ReportSource_No {
            get {
                return ResourceManager.GetString("lioE_ReportSource_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plantilla de Reporte Invalida.
        /// </summary>
        internal static string lioE_ReportTemplate_No {
            get {
                return ResourceManager.GetString("lioE_ReportTemplate_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio Invalido.
        /// </summary>
        internal static string lioE_Svc_No {
            get {
                return ResourceManager.GetString("lioE_Svc_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Comprobante Invalido..
        /// </summary>
        internal static string lioE_Tipo_No {
            get {
                return ResourceManager.GetString("lioE_Tipo_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Comprobante Invalido en Documento Asociado [{0}]..
        /// </summary>
        internal static string lioE_TipoAsoc_No {
            get {
                return ResourceManager.GetString("lioE_TipoAsoc_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Documento del Receptor Invalido..
        /// </summary>
        internal static string lioE_TipoReceptor_No {
            get {
                return ResourceManager.GetString("lioE_TipoReceptor_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Iva [{0}] invalido..
        /// </summary>
        internal static string lioE_Tiva_No {
            get {
                return ResourceManager.GetString("lioE_Tiva_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token con Formato Invalido.
        /// </summary>
        internal static string lioE_TokenNo {
            get {
                return ResourceManager.GetString("lioE_TokenNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de responsable Receptor Invalido.
        /// </summary>
        internal static string lioE_Tresp_No {
            get {
                return ResourceManager.GetString("lioE_Tresp_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tributo [{0}] invalido..
        /// </summary>
        internal static string lioE_Tributo_No {
            get {
                return ResourceManager.GetString("lioE_Tributo_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Bloqueado, Consulte al administrador.
        /// </summary>
        internal static string lioE_User_Block {
            get {
                return ResourceManager.GetString("lioE_User_Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario desahabilitado, consulte al administrador.
        /// </summary>
        internal static string lioE_UserDisabled {
            get {
                return ResourceManager.GetString("lioE_UserDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar Documento para procesar.
        /// </summary>
        internal static string lioL_Add {
            get {
                return ResourceManager.GetString("lioL_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprobante.
        /// </summary>
        internal static string lioL_Cbte {
            get {
                return ResourceManager.GetString("lioL_Cbte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar Archivo.
        /// </summary>
        internal static string lioL_FileDownload {
            get {
                return ResourceManager.GetString("lioL_FileDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        internal static string lioL_Find {
            get {
                return ResourceManager.GetString("lioL_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nat, Envio de Documento Electronico.
        /// </summary>
        internal static string lioL_Mail_Subject {
            get {
                return ResourceManager.GetString("lioL_Mail_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento .
        /// </summary>
        internal static string lioL_Print {
            get {
                return ResourceManager.GetString("lioL_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punto de Venta.
        /// </summary>
        internal static string lioL_Pventa {
            get {
                return ResourceManager.GetString("lioL_Pventa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respuesta Enviada en Archivo .
        /// </summary>
        internal static string lioL_Rta {
            get {
                return ResourceManager.GetString("lioL_Rta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respuesta Enviada via servicio.
        /// </summary>
        internal static string lioL_RtaWS {
            get {
                return ResourceManager.GetString("lioL_RtaWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destinatarios.
        /// </summary>
        internal static string lioL_Share {
            get {
                return ResourceManager.GetString("lioL_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc[{0}]=&gt;[{1}].
        /// </summary>
        internal static string lioM_DocOK {
            get {
                return ResourceManager.GetString("lioM_DocOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesamiento Finalizado.
        /// </summary>
        internal static string lioM_EndProc {
            get {
                return ResourceManager.GetString("lioM_EndProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesando Documentos de Cuit:.
        /// </summary>
        internal static string lioM_ProcCuit {
            get {
                return ResourceManager.GetString("lioM_ProcCuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesando Documento:.
        /// </summary>
        internal static string lioM_ProcDoc {
            get {
                return ResourceManager.GetString("lioM_ProcDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio de procesamiento de Documentos.
        /// </summary>
        internal static string lioM_StartProc {
            get {
                return ResourceManager.GetString("lioM_StartProc", resourceCulture);
            }
        }
    }
}
