//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nat.API.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nat.API.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respuesta de servicio invalida.
        /// </summary>
        internal static string lioE_AfipRespNo {
            get {
                return ResourceManager.GetString("lioE_AfipRespNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encabezado de Autorizacion Invalido.
        /// </summary>
        internal static string lioE_AuthHeaderNo {
            get {
                return ResourceManager.GetString("lioE_AuthHeaderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en Solicitud de CAE: {0}-{1}.
        /// </summary>
        internal static string lioE_CAE_Err {
            get {
                return ResourceManager.GetString("lioE_CAE_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en Solicitud de CAE.
        /// </summary>
        internal static string lioE_CAE_No {
            get {
                return ResourceManager.GetString("lioE_CAE_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones en Solicitud de CAE: {0}-{1}.
        /// </summary>
        internal static string lioE_CAE_Obs {
            get {
                return ResourceManager.GetString("lioE_CAE_Obs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en Consulta de CAE: {0}-{1}.
        /// </summary>
        internal static string lioE_CAEQry_Err {
            get {
                return ResourceManager.GetString("lioE_CAEQry_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en Consulta de CAE.
        /// </summary>
        internal static string lioE_CAEQry_No {
            get {
                return ResourceManager.GetString("lioE_CAEQry_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones en Consulta de CAE: {0}-{1}.
        /// </summary>
        internal static string lioE_CAEQry_Obs {
            get {
                return ResourceManager.GetString("lioE_CAEQry_Obs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concepto Invalido..
        /// </summary>
        internal static string lioE_Concepto_No {
            get {
                return ResourceManager.GetString("lioE_Concepto_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de Correlatividad: ultimo documento autorizado es {0} y se intenta autorizar el documento {1}..
        /// </summary>
        internal static string lioE_Correlat_No {
            get {
                return ResourceManager.GetString("lioE_Correlat_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotizacion Invalida.
        /// </summary>
        internal static string lioE_Cotiz_No {
            get {
                return ResourceManager.GetString("lioE_Cotiz_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacion de Autorizacion no puede modificarse.
        /// </summary>
        internal static string lioE_Doc_AuthInfoMod {
            get {
                return ResourceManager.GetString("lioE_Doc_AuthInfoMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento Autorizado no puede eliminarse.
        /// </summary>
        internal static string lioE_Doc_AuthNoDelete {
            get {
                return ResourceManager.GetString("lioE_Doc_AuthNoDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentos {0} en espera de predecesor.
        /// </summary>
        internal static string lioE_DocCorrel {
            get {
                return ResourceManager.GetString("lioE_DocCorrel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos del Documento {0} Invalidos.
        /// </summary>
        internal static string lioE_DocNoData {
            get {
                return ResourceManager.GetString("lioE_DocNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF No Encontrado.
        /// </summary>
        internal static string lioE_Document_NoPrint {
            get {
                return ResourceManager.GetString("lioE_Document_NoPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos de Entrada de Usuario no encontrados.
        /// </summary>
        internal static string lioE_DocumentUser_No {
            get {
                return ResourceManager.GetString("lioE_DocumentUser_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errores en Envio de Documento a AFIP:.
        /// </summary>
        internal static string lioE_HeaderAuth {
            get {
                return ResourceManager.GetString("lioE_HeaderAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importe Invalido..
        /// </summary>
        internal static string lioE_Importe_No {
            get {
                return ResourceManager.GetString("lioE_Importe_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item {0} invalido.
        /// </summary>
        internal static string lioE_Item_No {
            get {
                return ResourceManager.GetString("lioE_Item_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificacion Unica de Documento Invalida.
        /// </summary>
        internal static string lioE_Key_No {
            get {
                return ResourceManager.GetString("lioE_Key_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo Electronico Invalido.
        /// </summary>
        internal static string lioE_Mail_No {
            get {
                return ResourceManager.GetString("lioE_Mail_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda Invalida..
        /// </summary>
        internal static string lioE_Moneda_No {
            get {
                return ResourceManager.GetString("lioE_Moneda_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credenciales Invalidas.
        /// </summary>
        internal static string lioE_NoCreds {
            get {
                return ResourceManager.GetString("lioE_NoCreds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de documentos a procesar vacia.
        /// </summary>
        internal static string lioE_NoDocs {
            get {
                return ResourceManager.GetString("lioE_NoDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en Recuperacion de {0}, Detalle:{1}..
        /// </summary>
        internal static string lioE_NoGet {
            get {
                return ResourceManager.GetString("lioE_NoGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Datos Estaticos no Encontrada.
        /// </summary>
        internal static string lioE_NoStatics {
            get {
                return ResourceManager.GetString("lioE_NoStatics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero de Comprobante Invalido..
        /// </summary>
        internal static string lioE_Nro_No {
            get {
                return ResourceManager.GetString("lioE_Nro_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no Encontrada o con forrmato erroneo..
        /// </summary>
        internal static string lioE_ObjectNoF {
            get {
                return ResourceManager.GetString("lioE_ObjectNoF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no Encontrado o con forrmato erroneo..
        /// </summary>
        internal static string lioE_ObjectNoM {
            get {
                return ResourceManager.GetString("lioE_ObjectNoM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Opcional [{0}] invalido..
        /// </summary>
        internal static string lioE_Opcional_No {
            get {
                return ResourceManager.GetString("lioE_Opcional_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento Original no Encontrado.
        /// </summary>
        internal static string lioE_OriginalNo {
            get {
                return ResourceManager.GetString("lioE_OriginalNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permiso de Importacion {0} Invalido.
        /// </summary>
        internal static string lioE_PermisoNo {
            get {
                return ResourceManager.GetString("lioE_PermisoNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en Impresion de Documento.
        /// </summary>
        internal static string lioE_PrintNo {
            get {
                return ResourceManager.GetString("lioE_PrintNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejecucion Previa aun no finalizada.
        /// </summary>
        internal static string lioE_ProcRun {
            get {
                return ResourceManager.GetString("lioE_ProcRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punto de Venta Invalido..
        /// </summary>
        internal static string lioE_Pventa_No {
            get {
                return ResourceManager.GetString("lioE_Pventa_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punto de Venta Invalido en Documento Asociado [{0}]..
        /// </summary>
        internal static string lioE_PvtaAsoc_No {
            get {
                return ResourceManager.GetString("lioE_PvtaAsoc_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron Campos dentro de la Plantilla de Reporte.
        /// </summary>
        internal static string lioE_Report_NoFields {
            get {
                return ResourceManager.GetString("lioE_Report_NoFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Datos de Origen de Reporte Invalido.
        /// </summary>
        internal static string lioE_ReportAssembly_No {
            get {
                return ResourceManager.GetString("lioE_ReportAssembly_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origen de Datos no Coincide con Plantilla se espera [{0}] y se encontro [{1}].
        /// </summary>
        internal static string lioE_ReportAssembly_NoMatch {
            get {
                return ResourceManager.GetString("lioE_ReportAssembly_NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo de Reporte Invalido.
        /// </summary>
        internal static string lioE_ReportField_No {
            get {
                return ResourceManager.GetString("lioE_ReportField_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Tipo Tabla no posee columnas.
        /// </summary>
        internal static string lioE_ReportField_NoColumns {
            get {
                return ResourceManager.GetString("lioE_ReportField_NoColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encuentran lineas de factura a imprimir.
        /// </summary>
        internal static string lioE_ReportLines_No {
            get {
                return ResourceManager.GetString("lioE_ReportLines_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propiedad {0} no encontrada en Origen de Datos.
        /// </summary>
        internal static string lioE_ReportProperty_No {
            get {
                return ResourceManager.GetString("lioE_ReportProperty_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origen de Datos de Reporte Invalido.
        /// </summary>
        internal static string lioE_ReportSource_No {
            get {
                return ResourceManager.GetString("lioE_ReportSource_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plantilla de Reporte Invalida.
        /// </summary>
        internal static string lioE_ReportTemplate_No {
            get {
                return ResourceManager.GetString("lioE_ReportTemplate_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en envio de respuesta a Sistema Fecturados.
        /// </summary>
        internal static string lioE_RtaERP {
            get {
                return ResourceManager.GetString("lioE_RtaERP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio Invalido.
        /// </summary>
        internal static string lioE_Svc_No {
            get {
                return ResourceManager.GetString("lioE_Svc_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Comprobante Invalido..
        /// </summary>
        internal static string lioE_Tipo_No {
            get {
                return ResourceManager.GetString("lioE_Tipo_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Comprobante Invalido en Documento Asociado [{0}]..
        /// </summary>
        internal static string lioE_TipoAsoc_No {
            get {
                return ResourceManager.GetString("lioE_TipoAsoc_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Documento del Receptor Invalido..
        /// </summary>
        internal static string lioE_TipoReceptor_No {
            get {
                return ResourceManager.GetString("lioE_TipoReceptor_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Iva [{0}] invalido..
        /// </summary>
        internal static string lioE_Tiva_No {
            get {
                return ResourceManager.GetString("lioE_Tiva_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token con Formato Invalido.
        /// </summary>
        internal static string lioE_TokenNo {
            get {
                return ResourceManager.GetString("lioE_TokenNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de responsable Receptor Invalido.
        /// </summary>
        internal static string lioE_Tresp_No {
            get {
                return ResourceManager.GetString("lioE_Tresp_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tributo [{0}] invalido..
        /// </summary>
        internal static string lioE_Tributo_No {
            get {
                return ResourceManager.GetString("lioE_Tributo_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Bloqueado, Consulte al administrador.
        /// </summary>
        internal static string lioE_User_Block {
            get {
                return ResourceManager.GetString("lioE_User_Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario desahabilitado, consulte al administrador.
        /// </summary>
        internal static string lioE_UserDisabled {
            get {
                return ResourceManager.GetString("lioE_UserDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar Documento para procesar.
        /// </summary>
        internal static string lioL_Add {
            get {
                return ResourceManager.GetString("lioL_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprobante.
        /// </summary>
        internal static string lioL_Cbte {
            get {
                return ResourceManager.GetString("lioL_Cbte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar Archivo.
        /// </summary>
        internal static string lioL_FileDownload {
            get {
                return ResourceManager.GetString("lioL_FileDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        internal static string lioL_Find {
            get {
                return ResourceManager.GetString("lioL_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nat, Envio de Documento Electronico.
        /// </summary>
        internal static string lioL_Mail_Subject {
            get {
                return ResourceManager.GetString("lioL_Mail_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento .
        /// </summary>
        internal static string lioL_Print {
            get {
                return ResourceManager.GetString("lioL_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punto de Venta.
        /// </summary>
        internal static string lioL_Pventa {
            get {
                return ResourceManager.GetString("lioL_Pventa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respuesta Enviada en Archivo .
        /// </summary>
        internal static string lioL_Rta {
            get {
                return ResourceManager.GetString("lioL_Rta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respuesta Enviada via servicio.
        /// </summary>
        internal static string lioL_RtaWS {
            get {
                return ResourceManager.GetString("lioL_RtaWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destinatarios.
        /// </summary>
        internal static string lioL_Share {
            get {
                return ResourceManager.GetString("lioL_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc[{0}]=&gt;[{1}].
        /// </summary>
        internal static string lioM_DocOK {
            get {
                return ResourceManager.GetString("lioM_DocOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesamiento Finalizado.
        /// </summary>
        internal static string lioM_EndProc {
            get {
                return ResourceManager.GetString("lioM_EndProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesando Documentos de Cuit:.
        /// </summary>
        internal static string lioM_ProcCuit {
            get {
                return ResourceManager.GetString("lioM_ProcCuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesando Documento:.
        /// </summary>
        internal static string lioM_ProcDoc {
            get {
                return ResourceManager.GetString("lioM_ProcDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio de procesamiento de Documentos.
        /// </summary>
        internal static string lioM_StartProc {
            get {
                return ResourceManager.GetString("lioM_StartProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de campos adicionales del documento.
        /// </summary>
        internal static string lioP_coAdicionales {
            get {
                return ResourceManager.GetString("lioP_coAdicionales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de documentos asociados (ej. notas de crédito, débito, etc.).
        /// </summary>
        internal static string lioP_coAsociados {
            get {
                return ResourceManager.GetString("lioP_coAsociados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de compradores del documento (en caso de ser un documento compartido).
        /// </summary>
        internal static string lioP_coCompradores {
            get {
                return ResourceManager.GetString("lioP_coCompradores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de ítems del documento (productos o servicios facturados).
        /// </summary>
        internal static string lioP_coItems {
            get {
                return ResourceManager.GetString("lioP_coItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de ítems de tipo &quot;Código de Turismo&quot; (CT) del documento.
        /// </summary>
        internal static string lioP_coItemsCT {
            get {
                return ResourceManager.GetString("lioP_coItemsCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de alícuotas de IVA aplicables al documento.
        /// </summary>
        internal static string lioP_coIvas {
            get {
                return ResourceManager.GetString("lioP_coIvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de campos opcionales del documento.
        /// </summary>
        internal static string lioP_coOpcionales {
            get {
                return ResourceManager.GetString("lioP_coOpcionales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de otros tributos aplicables al documento.
        /// </summary>
        internal static string lioP_coOtrosTributos {
            get {
                return ResourceManager.GetString("lioP_coOtrosTributos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de permisos de exportación asociados al documento.
        /// </summary>
        internal static string lioP_coPermisosExp {
            get {
                return ResourceManager.GetString("lioP_coPermisosExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domicilio del receptor del documento.
        /// </summary>
        internal static string lioP_ioDomicilioReceptor {
            get {
                return ResourceManager.GetString("lioP_ioDomicilioReceptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotización de la moneda del documento.
        /// </summary>
        internal static string lioP_ivdblCotizacion {
            get {
                return ResourceManager.GetString("lioP_ivdblCotizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importe exento del documento.
        /// </summary>
        internal static string lioP_ivdblImporteExento {
            get {
                return ResourceManager.GetString("lioP_ivdblImporteExento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importe gravado del documento.
        /// </summary>
        internal static string lioP_ivdblImporteGravado {
            get {
                return ResourceManager.GetString("lioP_ivdblImporteGravado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importe total del IVA del documento.
        /// </summary>
        internal static string lioP_ivdblImporteIva {
            get {
                return ResourceManager.GetString("lioP_ivdblImporteIva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importe no gravado del documento.
        /// </summary>
        internal static string lioP_ivdblImporteNoGravado {
            get {
                return ResourceManager.GetString("lioP_ivdblImporteNoGravado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importe de otros tributos del documento.
        /// </summary>
        internal static string lioP_ivdblImporteOtrosTributos {
            get {
                return ResourceManager.GetString("lioP_ivdblImporteOtrosTributos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importe total del documento.
        /// </summary>
        internal static string lioP_ivdblImporteTotal {
            get {
                return ResourceManager.GetString("lioP_ivdblImporteTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número del comprobante.
        /// </summary>
        internal static string lioP_ivlngCbte {
            get {
                return ResourceManager.GetString("lioP_ivlngCbte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUIT del emisor del documento.
        /// </summary>
        internal static string lioP_ivlngCuitEmisor {
            get {
                return ResourceManager.GetString("lioP_ivlngCuitEmisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUIT del país del cliente asociado al documento.
        /// </summary>
        internal static string lioP_ivlngCuitPaisCliente {
            get {
                return ResourceManager.GetString("lioP_ivlngCuitPaisCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de documento del receptor.
        /// </summary>
        internal static string lioP_ivlngDocReceptor {
            get {
                return ResourceManager.GetString("lioP_ivlngDocReceptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Impositivo Expo.
        /// </summary>
        internal static string lioP_ivlngIDImpositivo {
            get {
                return ResourceManager.GetString("lioP_ivlngIDImpositivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número interno del documento.
        /// </summary>
        internal static string lioP_ivlngInt {
            get {
                return ResourceManager.GetString("lioP_ivlngInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concepto del documento (1: Productos, 2: Servicios, 3: Productos y Servicios).
        /// </summary>
        internal static string lioP_ivnroConcepto {
            get {
                return ResourceManager.GetString("lioP_ivnroConcepto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destino del comprobante (ej. Mercado Interno, Exportación, etc.).
        /// </summary>
        internal static string lioP_ivnroDestinoCmp {
            get {
                return ResourceManager.GetString("lioP_ivnroDestinoCmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma del documento (ej. Español, Inglés, etc.).
        /// </summary>
        internal static string lioP_ivnroIdioma {
            get {
                return ResourceManager.GetString("lioP_ivnroIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de documento (ej. Factura A, Factura B, etc.).
        /// </summary>
        internal static string lioP_ivnroTipoDoc {
            get {
                return ResourceManager.GetString("lioP_ivnroTipoDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de documento del receptor (ej. CUIT, CUIL, DNI, etc.).
        /// </summary>
        internal static string lioP_ivnroTipoDocReceptor {
            get {
                return ResourceManager.GetString("lioP_ivnroTipoDocReceptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de exportación del documento (ej. Definitiva, Temporal, etc.).
        /// </summary>
        internal static string lioP_ivnroTipoExpo {
            get {
                return ResourceManager.GetString("lioP_ivnroTipoExpo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de responsable del receptor (ej. Responsable Inscripto, Monotributista, etc.).
        /// </summary>
        internal static string lioP_ivnroTipoRespReceptor {
            get {
                return ResourceManager.GetString("lioP_ivnroTipoRespReceptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punto de venta del documento.
        /// </summary>
        internal static string lioP_ivnumPvta {
            get {
                return ResourceManager.GetString("lioP_ivnumPvta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atributo Integracion 1.
        /// </summary>
        internal static string lioP_ivstrAttr1 {
            get {
                return ResourceManager.GetString("lioP_ivstrAttr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atributo Integracion 2.
        /// </summary>
        internal static string lioP_ivstrAttr2 {
            get {
                return ResourceManager.GetString("lioP_ivstrAttr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atributo Integracion 3.
        /// </summary>
        internal static string lioP_ivstrAttr3 {
            get {
                return ResourceManager.GetString("lioP_ivstrAttr3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atributo Integracion 4.
        /// </summary>
        internal static string lioP_ivstrAttr4 {
            get {
                return ResourceManager.GetString("lioP_ivstrAttr4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atributo Integracion 5.
        /// </summary>
        internal static string lioP_ivstrAttr5 {
            get {
                return ResourceManager.GetString("lioP_ivstrAttr5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atributo Integracion 6.
        /// </summary>
        internal static string lioP_ivstrAttr6 {
            get {
                return ResourceManager.GetString("lioP_ivstrAttr6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atributo Integracion 7.
        /// </summary>
        internal static string lioP_ivstrAttr7 {
            get {
                return ResourceManager.GetString("lioP_ivstrAttr7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad de monedas extranjeras utilizadas en el documento.
        /// </summary>
        internal static string lioP_ivstrCanMisMonExt {
            get {
                return ResourceManager.GetString("lioP_ivstrCanMisMonExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del cliente asociado al documento.
        /// </summary>
        internal static string lioP_ivstrCliente {
            get {
                return ResourceManager.GetString("lioP_ivstrCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condiciones de pago del documento (ej. Contado, Crédito, etc.).
        /// </summary>
        internal static string lioP_ivstrCondPago {
            get {
                return ResourceManager.GetString("lioP_ivstrCondPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email del receptor del documento.
        /// </summary>
        internal static string lioP_ivstrEmail {
            get {
                return ResourceManager.GetString("lioP_ivstrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de emisión del documento.
        /// </summary>
        internal static string lioP_ivstrFechaEmision {
            get {
                return ResourceManager.GetString("lioP_ivstrFechaEmision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de inicio del servicio (si aplica).
        /// </summary>
        internal static string lioP_ivstrFechaServdesde {
            get {
                return ResourceManager.GetString("lioP_ivstrFechaServdesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de fin del servicio (si aplica).
        /// </summary>
        internal static string lioP_ivstrFechaServhasta {
            get {
                return ResourceManager.GetString("lioP_ivstrFechaServhasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de vencimiento del pago.
        /// </summary>
        internal static string lioP_ivstrFechaVtopago {
            get {
                return ResourceManager.GetString("lioP_ivstrFechaVtopago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador interno del cliente asociado al documento.
        /// </summary>
        internal static string lioP_ivstrIdCliente {
            get {
                return ResourceManager.GetString("lioP_ivstrIdCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador interno de la sucursal.
        /// </summary>
        internal static string lioP_ivstrIdSucursal {
            get {
                return ResourceManager.GetString("lioP_ivstrIdSucursal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoterms aplicables al documento (ej. FOB, CIF, etc.).
        /// </summary>
        internal static string lioP_ivstrIncoterms {
            get {
                return ResourceManager.GetString("lioP_ivstrIncoterms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción de los Incoterms aplicables al documento.
        /// </summary>
        internal static string lioP_ivstrIncotermsDs {
            get {
                return ResourceManager.GetString("lioP_ivstrIncotermsDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos de entrada del documento.
        /// </summary>
        internal static string lioP_ivstrInputData {
            get {
                return ResourceManager.GetString("lioP_ivstrInputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errores de carga del documento.
        /// </summary>
        internal static string lioP_ivstrLoadErrors {
            get {
                return ResourceManager.GetString("lioP_ivstrLoadErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda del documento (ej. ARS, USD, etc.).
        /// </summary>
        internal static string lioP_ivstrMoneda {
            get {
                return ResourceManager.GetString("lioP_ivstrMoneda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones del documento.
        /// </summary>
        internal static string lioP_ivstrObs {
            get {
                return ResourceManager.GetString("lioP_ivstrObs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones comerciales del documento.
        /// </summary>
        internal static string lioP_ivstrObsComerciales {
            get {
                return ResourceManager.GetString("lioP_ivstrObsComerciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permiso existente para la emisión del documento (si aplica).
        /// </summary>
        internal static string lioP_ivstrPermisoExistente {
            get {
                return ResourceManager.GetString("lioP_ivstrPermisoExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razón social del receptor del documento.
        /// </summary>
        internal static string lioP_ivstrRazonSocial {
            get {
                return ResourceManager.GetString("lioP_ivstrRazonSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web service utilizado para la emisión del documento.
        /// </summary>
        internal static string lioP_ivstrWs {
            get {
                return ResourceManager.GetString("lioP_ivstrWs", resourceCulture);
            }
        }
    }
}
