//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Applet.Nat.OracleCanonical.Update
{
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceDMLErrorMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceRowValErrorMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceAttrValErrorMessage))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/errors/")]
    public partial class ServiceErrorMessage : ServiceMessage
    {
        
        private object sdoObjectField;
        
        private string exceptionClassNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public object sdoObject
        {
            get
            {
                return this.sdoObjectField;
            }
            set
            {
                this.sdoObjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string exceptionClassName
        {
            get
            {
                return this.exceptionClassNameField;
            }
            set
            {
                this.exceptionClassNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="commonj.sdo/xml")]
    public partial class XMLInfo
    {
        
        private bool xmlElementField;
        
        private bool xmlElementFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool xmlElement
        {
            get
            {
                return this.xmlElementField;
            }
            set
            {
                this.xmlElementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool xmlElementSpecified
        {
            get
            {
                return this.xmlElementFieldSpecified;
            }
            set
            {
                this.xmlElementFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="commonj.sdo/java")]
    public partial class JavaInfo
    {
        
        private string javaClassField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string javaClass
        {
            get
            {
                return this.javaClassField;
            }
            set
            {
                this.javaClassField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="commonj.sdo")]
    public abstract partial class DataObject
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="commonj.sdo")]
    public partial class Property
    {
        
        private string[] aliasNameField;
        
        private System.Xml.XmlElement[] anyField;
        
        private string nameField;
        
        private bool manyField;
        
        private bool manyFieldSpecified;
        
        private bool containmentField;
        
        private bool containmentFieldSpecified;
        
        private string defaultField;
        
        private bool readOnlyField;
        
        private bool readOnlyFieldSpecified;
        
        private string typeField;
        
        private string oppositeField;
        
        private bool nullableField;
        
        private bool nullableFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("aliasName", Order=0)]
        public string[] aliasName
        {
            get
            {
                return this.aliasNameField;
            }
            set
            {
                this.aliasNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool many
        {
            get
            {
                return this.manyField;
            }
            set
            {
                this.manyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool manySpecified
        {
            get
            {
                return this.manyFieldSpecified;
            }
            set
            {
                this.manyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool containment
        {
            get
            {
                return this.containmentField;
            }
            set
            {
                this.containmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool containmentSpecified
        {
            get
            {
                return this.containmentFieldSpecified;
            }
            set
            {
                this.containmentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @default
        {
            get
            {
                return this.defaultField;
            }
            set
            {
                this.defaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool readOnly
        {
            get
            {
                return this.readOnlyField;
            }
            set
            {
                this.readOnlyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool readOnlySpecified
        {
            get
            {
                return this.readOnlyFieldSpecified;
            }
            set
            {
                this.readOnlyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string opposite
        {
            get
            {
                return this.oppositeField;
            }
            set
            {
                this.oppositeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool nullable
        {
            get
            {
                return this.nullableField;
            }
            set
            {
                this.nullableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nullableSpecified
        {
            get
            {
                return this.nullableFieldSpecified;
            }
            set
            {
                this.nullableFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="commonj.sdo")]
    public partial class Type
    {
        
        private string[] baseTypeField;
        
        private Property[] propertyField;
        
        private string[] aliasNameField;
        
        private System.Xml.XmlElement[] anyField;
        
        private string nameField;
        
        private string uriField;
        
        private bool dataTypeField;
        
        private bool dataTypeFieldSpecified;
        
        private bool openField;
        
        private bool openFieldSpecified;
        
        private bool sequencedField;
        
        private bool sequencedFieldSpecified;
        
        private bool abstractField;
        
        private bool abstractFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("baseType", DataType="anyURI", Order=0)]
        public string[] baseType
        {
            get
            {
                return this.baseTypeField;
            }
            set
            {
                this.baseTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("property", Order=1)]
        public Property[] property
        {
            get
            {
                return this.propertyField;
            }
            set
            {
                this.propertyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("aliasName", Order=2)]
        public string[] aliasName
        {
            get
            {
                return this.aliasNameField;
            }
            set
            {
                this.aliasNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=3)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string uri
        {
            get
            {
                return this.uriField;
            }
            set
            {
                this.uriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool dataType
        {
            get
            {
                return this.dataTypeField;
            }
            set
            {
                this.dataTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataTypeSpecified
        {
            get
            {
                return this.dataTypeFieldSpecified;
            }
            set
            {
                this.dataTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool open
        {
            get
            {
                return this.openField;
            }
            set
            {
                this.openField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool openSpecified
        {
            get
            {
                return this.openFieldSpecified;
            }
            set
            {
                this.openFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool sequenced
        {
            get
            {
                return this.sequencedField;
            }
            set
            {
                this.sequencedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sequencedSpecified
        {
            get
            {
                return this.sequencedFieldSpecified;
            }
            set
            {
                this.sequencedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool @abstract
        {
            get
            {
                return this.abstractField;
            }
            set
            {
                this.abstractField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool abstractSpecified
        {
            get
            {
                return this.abstractFieldSpecified;
            }
            set
            {
                this.abstractFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="commonj.sdo")]
    public partial class ChangeSummaryType
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private string createField;
        
        private string deleteField;
        
        private bool loggingField;
        
        private bool loggingFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string create
        {
            get
            {
                return this.createField;
            }
            set
            {
                this.createField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string delete
        {
            get
            {
                return this.deleteField;
            }
            set
            {
                this.deleteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool logging
        {
            get
            {
                return this.loggingField;
            }
            set
            {
                this.loggingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool loggingSpecified
        {
            get
            {
                return this.loggingFieldSpecified;
            }
            set
            {
                this.loggingFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="commonj.sdo")]
    public partial class XSDType
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="commonj.sdo")]
    public partial class ModelsType
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DataGraphType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="commonj.sdo")]
    public abstract partial class BaseDataGraphType
    {
        
        private ModelsType modelsField;
        
        private XSDType xsdField;
        
        private ChangeSummaryType changeSummaryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ModelsType models
        {
            get
            {
                return this.modelsField;
            }
            set
            {
                this.modelsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public XSDType xsd
        {
            get
            {
                return this.xsdField;
            }
            set
            {
                this.xsdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ChangeSummaryType changeSummary
        {
            get
            {
                return this.changeSummaryField;
            }
            set
            {
                this.changeSummaryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="commonj.sdo")]
    public partial class DataGraphType : BaseDataGraphType
    {
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/types/")]
    public partial class ServiceViewInfo
    {
        
        private string nameField;
        
        private string typeNameField;
        
        private bool canCreateField;
        
        private bool canUpdateField;
        
        private bool canMergeField;
        
        private bool canDeleteField;
        
        public ServiceViewInfo()
        {
            this.canCreateField = false;
            this.canUpdateField = false;
            this.canMergeField = false;
            this.canDeleteField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string typeName
        {
            get
            {
                return this.typeNameField;
            }
            set
            {
                this.typeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool canCreate
        {
            get
            {
                return this.canCreateField;
            }
            set
            {
                this.canCreateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool canUpdate
        {
            get
            {
                return this.canUpdateField;
            }
            set
            {
                this.canUpdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool canMerge
        {
            get
            {
                return this.canMergeField;
            }
            set
            {
                this.canMergeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool canDelete
        {
            get
            {
                return this.canDeleteField;
            }
            set
            {
                this.canDeleteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/types/")]
    public partial class AttrCtrlHints
    {
        
        private string attrNameField;
        
        private CtrlHint[] ctrlHintField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string attrName
        {
            get
            {
                return this.attrNameField;
            }
            set
            {
                this.attrNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ctrlHint", Order=1)]
        public CtrlHint[] ctrlHint
        {
            get
            {
                return this.ctrlHintField;
            }
            set
            {
                this.ctrlHintField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/types/")]
    public partial class CtrlHint
    {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/types/")]
    public partial class ObjAttrHints
    {
        
        private CtrlHint[] objHintField;
        
        private AttrCtrlHints[] attrHintsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("objHint", Order=0)]
        public CtrlHint[] objHint
        {
            get
            {
                return this.objHintField;
            }
            set
            {
                this.objHintField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attrHints", Order=1)]
        public AttrCtrlHints[] attrHints
        {
            get
            {
                return this.attrHintsField;
            }
            set
            {
                this.attrHintsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DataObjectResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DataHandlerResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StringResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ShortResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LongResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntegerResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FloatResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DoubleResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DateResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TimeResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TimestampResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BytesResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ByteResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BooleanResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BigIntegerResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BigDecimalResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/types/")]
    public partial class MethodResult
    {
        
        private ServiceMessage[] messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Message", Order=0)]
        public ServiceMessage[] Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceErrorMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceDMLErrorMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceRowValErrorMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceAttrValErrorMessage))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/errors/")]
    public partial class ServiceMessage
    {
        
        private string codeField;
        
        private string messageField;
        
        private string severityField;
        
        private ServiceMessage[] detailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string severity
        {
            get
            {
                return this.severityField;
            }
            set
            {
                this.severityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("detail", Order=3)]
        public ServiceMessage[] detail
        {
            get
            {
                return this.detailField;
            }
            set
            {
                this.detailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/types/")]
    public partial class DataObjectResult : MethodResult
    {
        
        private object[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Value", Order=0)]
        public object[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/types/")]
    public partial class DataHandlerResult : MethodResult
    {
        
        private byte[][] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Value", DataType="base64Binary", Order=0)]
        public byte[][] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/types/")]
    public partial class StringResult : MethodResult
    {
        
        private string[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Value", Order=0)]
        public string[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/types/")]
    public partial class ShortResult : MethodResult
    {
        
        private short[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Value", Order=0)]
        public short[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/types/")]
    public partial class LongResult : MethodResult
    {
        
        private long[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Value", Order=0)]
        public long[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/types/")]
    public partial class IntegerResult : MethodResult
    {
        
        private int[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Value", Order=0)]
        public int[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/types/")]
    public partial class FloatResult : MethodResult
    {
        
        private float[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Value", Order=0)]
        public float[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/types/")]
    public partial class DoubleResult : MethodResult
    {
        
        private double[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Value", Order=0)]
        public double[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/types/")]
    public partial class DateResult : MethodResult
    {
        
        private System.DateTime[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Value", DataType="date", Order=0)]
        public System.DateTime[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/types/")]
    public partial class TimeResult : MethodResult
    {
        
        private System.DateTime[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Value", DataType="time", Order=0)]
        public System.DateTime[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/types/")]
    public partial class TimestampResult : MethodResult
    {
        
        private System.DateTime[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Value", Order=0)]
        public System.DateTime[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/types/")]
    public partial class BytesResult : MethodResult
    {
        
        private byte[][] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Value", DataType="hexBinary", Order=0)]
        public byte[][] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/types/")]
    public partial class ByteResult : MethodResult
    {
        
        private sbyte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Value", Order=0)]
        public sbyte[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/types/")]
    public partial class BooleanResult : MethodResult
    {
        
        private bool[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Value", Order=0)]
        public bool[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/types/")]
    public partial class BigIntegerResult : MethodResult
    {
        
        private string[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Value", DataType="integer", Order=0)]
        public string[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/types/")]
    public partial class BigDecimalResult : MethodResult
    {
        
        private decimal[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Value", Order=0)]
        public decimal[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/types/")]
    public partial class ProcessControl
    {
        
        private ReturnMode returnModeField;
        
        private bool returnModeFieldSpecified;
        
        private ReturnMode exceptionReturnModeField;
        
        private bool exceptionReturnModeFieldSpecified;
        
        private bool partialFailureAllowedField;
        
        public ProcessControl()
        {
            this.partialFailureAllowedField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ReturnMode returnMode
        {
            get
            {
                return this.returnModeField;
            }
            set
            {
                this.returnModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnModeSpecified
        {
            get
            {
                return this.returnModeFieldSpecified;
            }
            set
            {
                this.returnModeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ReturnMode exceptionReturnMode
        {
            get
            {
                return this.exceptionReturnModeField;
            }
            set
            {
                this.exceptionReturnModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool exceptionReturnModeSpecified
        {
            get
            {
                return this.exceptionReturnModeFieldSpecified;
            }
            set
            {
                this.exceptionReturnModeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool partialFailureAllowed
        {
            get
            {
                return this.partialFailureAllowedField;
            }
            set
            {
                this.partialFailureAllowedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/types/")]
    public enum ReturnMode
    {
        
        /// <remarks/>
        Full,
        
        /// <remarks/>
        Key,
        
        /// <remarks/>
        None,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/types/")]
    public partial class FindControl
    {
        
        private bool retrieveAllTranslationsField;
        
        public FindControl()
        {
            this.retrieveAllTranslationsField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool retrieveAllTranslations
        {
            get
            {
                return this.retrieveAllTranslationsField;
            }
            set
            {
                this.retrieveAllTranslationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/types/")]
    public partial class SortAttribute
    {
        
        private string nameField;
        
        private bool descendingField;
        
        public SortAttribute()
        {
            this.descendingField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool descending
        {
            get
            {
                return this.descendingField;
            }
            set
            {
                this.descendingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/types/")]
    public partial class ViewCriteriaItem
    {
        
        private Conjunction conjunctionField;
        
        private bool conjunctionFieldSpecified;
        
        private bool upperCaseCompareField;
        
        private string attributeField;
        
        private string operatorField;
        
        private object[] itemsField;
        
        public ViewCriteriaItem()
        {
            this.upperCaseCompareField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Conjunction conjunction
        {
            get
            {
                return this.conjunctionField;
            }
            set
            {
                this.conjunctionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool conjunctionSpecified
        {
            get
            {
                return this.conjunctionFieldSpecified;
            }
            set
            {
                this.conjunctionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool upperCaseCompare
        {
            get
            {
                return this.upperCaseCompareField;
            }
            set
            {
                this.upperCaseCompareField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string attribute
        {
            get
            {
                return this.attributeField;
            }
            set
            {
                this.attributeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string @operator
        {
            get
            {
                return this.operatorField;
            }
            set
            {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nested", typeof(ViewCriteria), Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("value", typeof(string), Order=4)]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/types/")]
    public enum Conjunction
    {
        
        /// <remarks/>
        And,
        
        /// <remarks/>
        Or,
        
        /// <remarks/>
        Not,
        
        /// <remarks/>
        AndNot,
        
        /// <remarks/>
        OrNot,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/types/")]
    public partial class ViewCriteria
    {
        
        private Conjunction conjunctionField;
        
        private bool conjunctionFieldSpecified;
        
        private ViewCriteriaRow[] groupField;
        
        private ViewCriteria[] nestedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Conjunction conjunction
        {
            get
            {
                return this.conjunctionField;
            }
            set
            {
                this.conjunctionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool conjunctionSpecified
        {
            get
            {
                return this.conjunctionFieldSpecified;
            }
            set
            {
                this.conjunctionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("group", Order=1)]
        public ViewCriteriaRow[] group
        {
            get
            {
                return this.groupField;
            }
            set
            {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nested", Order=2)]
        public ViewCriteria[] nested
        {
            get
            {
                return this.nestedField;
            }
            set
            {
                this.nestedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/types/")]
    public partial class ViewCriteriaRow
    {
        
        private Conjunction conjunctionField;
        
        private bool conjunctionFieldSpecified;
        
        private bool upperCaseCompareField;
        
        private ViewCriteriaItem[] itemField;
        
        public ViewCriteriaRow()
        {
            this.upperCaseCompareField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Conjunction conjunction
        {
            get
            {
                return this.conjunctionField;
            }
            set
            {
                this.conjunctionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool conjunctionSpecified
        {
            get
            {
                return this.conjunctionFieldSpecified;
            }
            set
            {
                this.conjunctionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool upperCaseCompare
        {
            get
            {
                return this.upperCaseCompareField;
            }
            set
            {
                this.upperCaseCompareField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("item", Order=2)]
        public ViewCriteriaItem[] item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ChildFindCriteria))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/types/")]
    public partial class FindCriteria
    {
        
        private int fetchStartField;
        
        private int fetchSizeField;
        
        private ViewCriteria filterField;
        
        private SortAttribute[] sortOrderField;
        
        private string[] findAttributeField;
        
        private bool excludeAttributeField;
        
        private ChildFindCriteria[] childFindCriteriaField;
        
        public FindCriteria()
        {
            this.fetchStartField = 0;
            this.fetchSizeField = -1;
            this.excludeAttributeField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int fetchStart
        {
            get
            {
                return this.fetchStartField;
            }
            set
            {
                this.fetchStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int fetchSize
        {
            get
            {
                return this.fetchSizeField;
            }
            set
            {
                this.fetchSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ViewCriteria filter
        {
            get
            {
                return this.filterField;
            }
            set
            {
                this.filterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("sortAttribute", IsNullable=false)]
        public SortAttribute[] sortOrder
        {
            get
            {
                return this.sortOrderField;
            }
            set
            {
                this.sortOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("findAttribute", Order=4)]
        public string[] findAttribute
        {
            get
            {
                return this.findAttributeField;
            }
            set
            {
                this.findAttributeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool excludeAttribute
        {
            get
            {
                return this.excludeAttributeField;
            }
            set
            {
                this.excludeAttributeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("childFindCriteria", Order=6)]
        public ChildFindCriteria[] childFindCriteria
        {
            get
            {
                return this.childFindCriteriaField;
            }
            set
            {
                this.childFindCriteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/types/")]
    public partial class ChildFindCriteria : FindCriteria
    {
        
        private string childAttrNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string childAttrName
        {
            get
            {
                return this.childAttrNameField;
            }
            set
            {
                this.childAttrNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/oracleas/schema/oracle-fault-11_0")]
    public partial class detail
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/oracleas/schema/oracle-fault-11_0")]
    public partial class FaultType
    {
        
        private System.Xml.XmlQualifiedName faultcodeField;
        
        private string faultstringField;
        
        private string faultactorField;
        
        private detail detailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.Xml.XmlQualifiedName faultcode
        {
            get
            {
                return this.faultcodeField;
            }
            set
            {
                this.faultcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string faultstring
        {
            get
            {
                return this.faultstringField;
            }
            set
            {
                this.faultstringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI", Order=2)]
        public string faultactor
        {
            get
            {
                return this.faultactorField;
            }
            set
            {
                this.faultactorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public detail detail
        {
            get
            {
                return this.detailField;
            }
            set
            {
                this.detailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegration" +
        "Service/")]
    public partial class ErpObjectDetails
    {
        
        private string entityNameField;
        
        private string contextValueField;
        
        private string userKeyAField;
        
        private string userKeyBField;
        
        private string userKeyCField;
        
        private string userKeyDField;
        
        private string userKeyEField;
        
        private string userKeyFField;
        
        private string userKeyGField;
        
        private string userKeyHField;
        
        private string dFFAttributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string EntityName
        {
            get
            {
                return this.entityNameField;
            }
            set
            {
                this.entityNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string ContextValue
        {
            get
            {
                return this.contextValueField;
            }
            set
            {
                this.contextValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string UserKeyA
        {
            get
            {
                return this.userKeyAField;
            }
            set
            {
                this.userKeyAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string UserKeyB
        {
            get
            {
                return this.userKeyBField;
            }
            set
            {
                this.userKeyBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string UserKeyC
        {
            get
            {
                return this.userKeyCField;
            }
            set
            {
                this.userKeyCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string UserKeyD
        {
            get
            {
                return this.userKeyDField;
            }
            set
            {
                this.userKeyDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string UserKeyE
        {
            get
            {
                return this.userKeyEField;
            }
            set
            {
                this.userKeyEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string UserKeyF
        {
            get
            {
                return this.userKeyFField;
            }
            set
            {
                this.userKeyFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string UserKeyG
        {
            get
            {
                return this.userKeyGField;
            }
            set
            {
                this.userKeyGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string UserKeyH
        {
            get
            {
                return this.userKeyHField;
            }
            set
            {
                this.userKeyHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string DFFAttributes
        {
            get
            {
                return this.dFFAttributesField;
            }
            set
            {
                this.dFFAttributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegration" +
        "Service/")]
    public partial class DocumentDetails
    {
        
        private byte[] contentField;
        
        private string fileNameField;
        
        private string contentTypeField;
        
        private string documentTitleField;
        
        private string documentAuthorField;
        
        private string documentSecurityGroupField;
        
        private string documentAccountField;
        
        private string documentNameField;
        
        private string documentIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true, Order=0)]
        public byte[] Content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string FileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string ContentType
        {
            get
            {
                return this.contentTypeField;
            }
            set
            {
                this.contentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string DocumentTitle
        {
            get
            {
                return this.documentTitleField;
            }
            set
            {
                this.documentTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string DocumentAuthor
        {
            get
            {
                return this.documentAuthorField;
            }
            set
            {
                this.documentAuthorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string DocumentSecurityGroup
        {
            get
            {
                return this.documentSecurityGroupField;
            }
            set
            {
                this.documentSecurityGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string DocumentAccount
        {
            get
            {
                return this.documentAccountField;
            }
            set
            {
                this.documentAccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string DocumentName
        {
            get
            {
                return this.documentNameField;
            }
            set
            {
                this.documentNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string DocumentId
        {
            get
            {
                return this.documentIdField;
            }
            set
            {
                this.documentIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/errors/")]
    public partial class ServiceDMLErrorMessage : ServiceErrorMessage
    {
        
        private string operationField;
        
        private string statementField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string operation
        {
            get
            {
                return this.operationField;
            }
            set
            {
                this.operationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string statement
        {
            get
            {
                return this.statementField;
            }
            set
            {
                this.statementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/errors/")]
    public partial class ServiceRowValErrorMessage : ServiceErrorMessage
    {
        
        private string objectNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string objectName
        {
            get
            {
                return this.objectNameField;
            }
            set
            {
                this.objectNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/errors/")]
    public partial class ServiceAttrValErrorMessage : ServiceErrorMessage
    {
        
        private string attributeNameField;
        
        private string attributeValueField;
        
        private string objectNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string attributeName
        {
            get
            {
                return this.attributeNameField;
            }
            set
            {
                this.attributeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string attributeValue
        {
            get
            {
                return this.attributeValueField;
            }
            set
            {
                this.attributeValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string objectName
        {
            get
            {
                return this.objectNameField;
            }
            set
            {
                this.objectNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegration" +
        "Service/", ConfigurationName="Applet.Nat.OracleCanonical.Update.ErpObjectDFFUpdateServiceResponse")]
    public interface ErpObjectDFFUpdateServiceResponse
    {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://xmlns.oracle.com/oracleas/schema/oracle-fault-11_0/Fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(XMLInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(JavaInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseDataGraphType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceViewInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ObjAttrHints))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcessControl))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FindControl))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FindCriteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FaultType))]
        System.Threading.Tasks.Task onFaultAsync(Applet.Nat.OracleCanonical.Update.onFault request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegration" +
            "Service/updateDffEntityDetailsAsyncResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(XMLInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(JavaInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseDataGraphType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceViewInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ObjAttrHints))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcessControl))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FindControl))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FindCriteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FaultType))]
        System.Threading.Tasks.Task updateDffEntityDetailsAsyncResponseAsync(Applet.Nat.OracleCanonical.Update.updateDffEntityDetailsAsyncResponse request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Fault", WrapperNamespace="http://xmlns.oracle.com/oracleas/schema/oracle-fault-11_0", IsWrapped=true)]
    public partial class onFault
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/oracleas/schema/oracle-fault-11_0", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Xml.XmlQualifiedName faultcode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/oracleas/schema/oracle-fault-11_0", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string faultstring;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/oracleas/schema/oracle-fault-11_0", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI")]
        public string faultactor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/oracleas/schema/oracle-fault-11_0", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Applet.Nat.OracleCanonical.Update.detail detail;
        
        public onFault()
        {
        }
        
        public onFault(System.Xml.XmlQualifiedName faultcode, string faultstring, string faultactor, Applet.Nat.OracleCanonical.Update.detail detail)
        {
            this.faultcode = faultcode;
            this.faultstring = faultstring;
            this.faultactor = faultactor;
            this.detail = detail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateDffEntityDetailsAsyncResponse", WrapperNamespace="http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegration" +
        "Service/types/", IsWrapped=true)]
    public partial class updateDffEntityDetailsAsyncResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegration" +
            "Service/types/", Order=0)]
        public string result;
        
        public updateDffEntityDetailsAsyncResponse()
        {
        }
        
        public updateDffEntityDetailsAsyncResponse(string result)
        {
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ErpObjectDFFUpdateServiceResponseChannel : Applet.Nat.OracleCanonical.Update.ErpObjectDFFUpdateServiceResponse, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ErpObjectDFFUpdateServiceResponseClient : System.ServiceModel.ClientBase<Applet.Nat.OracleCanonical.Update.ErpObjectDFFUpdateServiceResponse>, Applet.Nat.OracleCanonical.Update.ErpObjectDFFUpdateServiceResponse
    {
        
        public ErpObjectDFFUpdateServiceResponseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task Applet.Nat.OracleCanonical.Update.ErpObjectDFFUpdateServiceResponse.onFaultAsync(Applet.Nat.OracleCanonical.Update.onFault request)
        {
            return base.Channel.onFaultAsync(request);
        }
        
        public System.Threading.Tasks.Task onFaultAsync(System.Xml.XmlQualifiedName faultcode, string faultstring, string faultactor, Applet.Nat.OracleCanonical.Update.detail detail)
        {
            Applet.Nat.OracleCanonical.Update.onFault inValue = new Applet.Nat.OracleCanonical.Update.onFault();
            inValue.faultcode = faultcode;
            inValue.faultstring = faultstring;
            inValue.faultactor = faultactor;
            inValue.detail = detail;
            return ((Applet.Nat.OracleCanonical.Update.ErpObjectDFFUpdateServiceResponse)(this)).onFaultAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task Applet.Nat.OracleCanonical.Update.ErpObjectDFFUpdateServiceResponse.updateDffEntityDetailsAsyncResponseAsync(Applet.Nat.OracleCanonical.Update.updateDffEntityDetailsAsyncResponse request)
        {
            return base.Channel.updateDffEntityDetailsAsyncResponseAsync(request);
        }
        
        public System.Threading.Tasks.Task updateDffEntityDetailsAsyncResponseAsync(string result)
        {
            Applet.Nat.OracleCanonical.Update.updateDffEntityDetailsAsyncResponse inValue = new Applet.Nat.OracleCanonical.Update.updateDffEntityDetailsAsyncResponse();
            inValue.result = result;
            return ((Applet.Nat.OracleCanonical.Update.ErpObjectDFFUpdateServiceResponse)(this)).updateDffEntityDetailsAsyncResponseAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegration" +
        "Service/", ConfigurationName="Applet.Nat.OracleCanonical.Update.ErpObjectDFFUpdateService")]
    public interface ErpObjectDFFUpdateService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegration" +
            "Service/ErpObjectDFFUpdateService/updateDffEntityDetailsRequest", ReplyAction="http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegration" +
            "Service/ErpObjectDFFUpdateService/updateDffEntityDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Applet.Nat.OracleCanonical.Update.ServiceErrorMessage), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="ServiceErrorMessage", Namespace="http://xmlns.oracle.com/adf/svc/errors/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(XMLInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(JavaInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseDataGraphType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceViewInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ObjAttrHints))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcessControl))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FindControl))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FindCriteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FaultType))]
        System.Threading.Tasks.Task<Applet.Nat.OracleCanonical.Update.updateDffEntityDetailsResponse> updateDffEntityDetailsAsync(Applet.Nat.OracleCanonical.Update.updateDffEntityDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegration" +
            "Service/updateDffEntityDetailsAsync")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(XMLInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(JavaInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseDataGraphType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceViewInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ObjAttrHints))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProcessControl))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FindControl))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FindCriteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FaultType))]
        System.Threading.Tasks.Task updateDffEntityDetailsAsyncAsync(Applet.Nat.OracleCanonical.Update.updateDffEntityDetailsAsync request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateDffEntityDetails", WrapperNamespace="http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegration" +
        "Service/types/", IsWrapped=true)]
    public partial class updateDffEntityDetailsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegration" +
            "Service/types/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Applet.Nat.OracleCanonical.Update.DocumentDetails document;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegration" +
            "Service/types/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string operationMode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegration" +
            "Service/types/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Applet.Nat.OracleCanonical.Update.ErpObjectDetails @object;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegration" +
            "Service/types/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string notificationCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegration" +
            "Service/types/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string callbackURL;
        
        public updateDffEntityDetailsRequest()
        {
        }
        
        public updateDffEntityDetailsRequest(Applet.Nat.OracleCanonical.Update.DocumentDetails document, string operationMode, Applet.Nat.OracleCanonical.Update.ErpObjectDetails @object, string notificationCode, string callbackURL)
        {
            this.document = document;
            this.operationMode = operationMode;
            this.@object = @object;
            this.notificationCode = notificationCode;
            this.callbackURL = callbackURL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateDffEntityDetailsResponse", WrapperNamespace="http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegration" +
        "Service/types/", IsWrapped=true)]
    public partial class updateDffEntityDetailsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegration" +
            "Service/types/", Order=0)]
        public string result;
        
        public updateDffEntityDetailsResponse()
        {
        }
        
        public updateDffEntityDetailsResponse(string result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateDffEntityDetailsAsync", WrapperNamespace="http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegration" +
        "Service/types/", IsWrapped=true)]
    public partial class updateDffEntityDetailsAsync
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegration" +
            "Service/types/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Applet.Nat.OracleCanonical.Update.DocumentDetails document;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegration" +
            "Service/types/", Order=1)]
        public string operationMode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegration" +
            "Service/types/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Applet.Nat.OracleCanonical.Update.ErpObjectDetails @object;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegration" +
            "Service/types/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string notificationCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegration" +
            "Service/types/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string callbackURL;
        
        public updateDffEntityDetailsAsync()
        {
        }
        
        public updateDffEntityDetailsAsync(Applet.Nat.OracleCanonical.Update.DocumentDetails document, string operationMode, Applet.Nat.OracleCanonical.Update.ErpObjectDetails @object, string notificationCode, string callbackURL)
        {
            this.document = document;
            this.operationMode = operationMode;
            this.@object = @object;
            this.notificationCode = notificationCode;
            this.callbackURL = callbackURL;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ErpObjectDFFUpdateServiceChannel : Applet.Nat.OracleCanonical.Update.ErpObjectDFFUpdateService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ErpObjectDFFUpdateServiceClient : System.ServiceModel.ClientBase<Applet.Nat.OracleCanonical.Update.ErpObjectDFFUpdateService>, Applet.Nat.OracleCanonical.Update.ErpObjectDFFUpdateService
    {
        
        public ErpObjectDFFUpdateServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Applet.Nat.OracleCanonical.Update.updateDffEntityDetailsResponse> Applet.Nat.OracleCanonical.Update.ErpObjectDFFUpdateService.updateDffEntityDetailsAsync(Applet.Nat.OracleCanonical.Update.updateDffEntityDetailsRequest request)
        {
            return base.Channel.updateDffEntityDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Applet.Nat.OracleCanonical.Update.updateDffEntityDetailsResponse> updateDffEntityDetailsAsync(Applet.Nat.OracleCanonical.Update.DocumentDetails document, string operationMode, Applet.Nat.OracleCanonical.Update.ErpObjectDetails @object, string notificationCode, string callbackURL)
        {
            Applet.Nat.OracleCanonical.Update.updateDffEntityDetailsRequest inValue = new Applet.Nat.OracleCanonical.Update.updateDffEntityDetailsRequest();
            inValue.document = document;
            inValue.operationMode = operationMode;
            inValue.@object = @object;
            inValue.notificationCode = notificationCode;
            inValue.callbackURL = callbackURL;
            return ((Applet.Nat.OracleCanonical.Update.ErpObjectDFFUpdateService)(this)).updateDffEntityDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task Applet.Nat.OracleCanonical.Update.ErpObjectDFFUpdateService.updateDffEntityDetailsAsyncAsync(Applet.Nat.OracleCanonical.Update.updateDffEntityDetailsAsync request)
        {
            return base.Channel.updateDffEntityDetailsAsyncAsync(request);
        }
        
        public System.Threading.Tasks.Task updateDffEntityDetailsAsyncAsync(Applet.Nat.OracleCanonical.Update.DocumentDetails document, string operationMode, Applet.Nat.OracleCanonical.Update.ErpObjectDetails @object, string notificationCode, string callbackURL)
        {
            Applet.Nat.OracleCanonical.Update.updateDffEntityDetailsAsync inValue = new Applet.Nat.OracleCanonical.Update.updateDffEntityDetailsAsync();
            inValue.document = document;
            inValue.operationMode = operationMode;
            inValue.@object = @object;
            inValue.notificationCode = notificationCode;
            inValue.callbackURL = callbackURL;
            return ((Applet.Nat.OracleCanonical.Update.ErpObjectDFFUpdateService)(this)).updateDffEntityDetailsAsyncAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
    }
}
