name: NatApi

on:
  push:
    branches:
      - main
      - qa
  pull_request:
    branches:
      - main
      - qa

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Compile the solution
    - name: Compile solution
      run: dotnet build --configuration Release --no-restore

    # Publish the project
    - name: Publish project
      run: dotnet publish --configuration Release --output ./publish

    # Create artifact
    - name: Create deployment artifact
      run: zip -r deployment-package.zip ./publish

    # Upload artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: deployment-package
        path: deployment-package.zip